from collections.abc import Sequence
from datetime import UTC, datetime
from typing import Any

from pydantic import BaseModel, Field


class Meta(BaseModel):
    """
    Metadata about the response, such as timestamp, status, and optional request identifiers.
    """

    timestamp: str = Field(
        default_factory=lambda: datetime.now(UTC).isoformat(),
        description="Timestamp when the response was generated, in ISO 8601 format.",
    )
    success: bool = Field(
        default_factory=lambda: True,
        description="Indicates the overall status of the response (e.g., 'success' or 'error').",
    )
    request_id: str | None = Field(
        default_factory=lambda: None,
        description="Optional unique identifier for tracking the request.",
    )


class ResponseEnvelope(BaseModel):
    """
    Standard API response envelope for successful results.

    This model wraps any successful response payload in a consistent format,
    providing additional metadata for observability, debugging, and consistency
    across endpoints.
    """

    data: Any | None = Field(None, description="The main response payload.")
    meta: Meta = Field(
        default_factory=lambda: Meta(),
        description="Metadata about the response (timestamp, status, etc.).",
    )


class ErrorResponse(BaseModel):
    """
    Standardized error response format, based on RFC 7807 (Problem Details for HTTP APIs).
    """

    type: str = Field(..., description="A URI reference that identifies the problem type.")
    title: str = Field(..., description="A short, human-readable summary of the problem type.")
    status: int = Field(
        ...,
        description="The HTTP status code generated by the origin server "
        "for this occurrence of the problem.",
    )
    detail: str = Field(
        ..., description="A human-readable explanation specific to this occurrence of the problem."
    )
    instance: str | None = Field(
        None, description="A URI reference that identifies the specific occurrence of the problem."
    )
    errors: Sequence[Any] | dict[str, Any] | None = Field(
        default_factory=lambda: None,
        description="Additional error details, such as validation issues.",
    )
    meta: Meta = Field(
        default_factory=lambda: Meta(success=False),
        description="Metadata about the error response (timestamp, status, etc.).",
    )
